media_folder: static/assets
public_folder: assets
collections:
  - name: cards
    label: Cards
    folder: src/content/cards
    create: true
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: card }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: buttonLabel, label: "Button Label" }
      - { name: buttonUrl, label: "Button Url" }
      - { name: cardImage, label: "Card Image", widget: image }
      - { name: date, label: Published, widget: datetime }
  - name: quick-links
    label: "Quick Links"
    folder: src/content/quick-links
    create: true
    fields:
      - { name: templateKey, label: "Template Key", widget: hidden, default: quick-link }
      - { name: title, label: "Page Title" }
      - { name: pageUrl, label: "Page URL" }
      - { name: order, label: "Order in footer" }
  - name: pages
    label: Pages
    files:
      - file: src/content/home.md
        name: home
        label: Home
        editor:
          preview: false
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: home-page }
          - name: taglineSection
            label: "Tag Line Section"
            widget: object
            fields:
              - { name: text, label: Text, widget: markdown }
              - { name: buttonLabel, label: "Button Label" }
              - { name: buttonUrl, label: "Button URL" }
          - name: firstCallToActionSection
            label: "First Call to Action Section"
            widget: object
            fields:
              - { name: description, label: Description }
              - { name: buttonUrl, label: "Button URL" }
              - { name: buttonLabel, label: "Button Label" }
          - name: secondCallToActionSection
            label: "Second Call to Action Section"
            widget: object
            fields:
              - { name: description, label: Description }
              - { name: buttonUrl, label: "Button URL" }
              - { name: buttonLabel, label: "Button Label" }
          - name: thirdCallToActionSection
            label: "Third Call to Action Section"
            widget: object
            fields:
              - { name: description, label: Description }
              - { name: buttonUrl, label: "Button URL" }
              - { name: buttonLabel, label: "Button Label" }
          - name: impactUsageSection
            label: "Impace Usage Section"
            widget: object
            fields:
              - { name: heading, label: Heading }
              - { name: image, label: Image, widget: image }
              - { name: totalBooks, label: "Total Books" }
              - { name: totalViews, label: "Total Views" }
      - file: "src/content/about.md"
        name: about
        label: About
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: about-page }
          - { name: title, label: About }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/contact.md"
        name: contact
        label: Contact
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: contact-page }
          - { name: title, label: Contact }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/librarians.md"
        name: librarians
        label: Librarians
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: librarians-page }
          - { name: title, label: Librarians }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/publishers.md"
        name: publishers
        label: Publishers
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: publishers-page }
          - { name: title, label: Publishers }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/societies.md"
        name: societies
        label: Societies
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: societies-page }
          - { name: title, label: Societies }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/collection.md"
        name: collection
        label: Collection
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: collection-page }
          - { name: title, label: Collection }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/help.md"
        name: help
        label: Help
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: help-page }
          - { name: title, label: Help }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/faqs.md"
        name: faqs
        label: FAQs
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: faqs-page }
          - { name: title, label: FAQs }
          - { name: body, label: Body, widget: markdown }
      - file: "src/content/impact.md"
        name: impact
        label: Impact
        fields:
          - { name: templateKey, label: "Template Key", widget: hidden, default: impact-page }
          - { name: title, label: Impact }
          - { name: readershipMapDescription, label: "Readership Map Description", widget: markdown }
          - { name: googleDataStudioDescription, label: "Google Data Studio Description", widget: markdown }
